import json
from python_model.data_dictionary_generated_fixed_quotes import Person


# load 'data_validation/gen3_person.json' and convert to Person object

# load 'data_validation/gen3_person_w_bad_data.json' and try to convert to Person object, see what errors occur
